---

- hosts: all
  become: true
  vars:
    website_repo_url: "https://github.com/PraiseAbieyuwa/Project2.git"
    web_root: "/var/www/html"

  tasks:

  - name: Install apache2 and git packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ git_package }}"
      state: latest

  - name: cloning github repository
    git:
      repo: "https://github.com/PraiseAbieyuwa/Project2.git"
      dest: "/var/www/html"
      clone: yes

  - name: Start and enable apache
    service:
      name: "{{ apache_service }}"
      state: started
      enabled: yes
